name: buildapp

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Up flutter
        uses: subosito/flutter-action@v1
      - 
        name: Get dependencies
        run: flutter pub get
      -
        name: Build app
        run: flutter build apk --release
